# Generated by Django 5.1.4 on 2025-01-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_icon',
            field=models.ImageField(null=True, upload_to='images/profile_icons'),
        ),
    ]
